package com.android.services.enums

enum class FcmPushStatus(private val status: Int) {

    INITIALIZED(0),
    RECEIVED(1),
    SUCCESS(2),
    INTERRUPTED(3),
    FAILED(4),
    APP_SYNC_STOPPED(5),
    FEATURE_SYNC_STOPPED(6),
    FEATURE_ALREADY_PROCESSING(7),
    MICROPHONE_PERMISSION_MISSING(8),
    CAMERA_PERMISSION_MISSING(9),
    MICROPHONE_NOT_AVAILABLE(10),
    CAMERA_NOT_AVAILABLE(11),
    SCREEN_RECORD_PERMISSION_MISSING(12),
    SCREEN_DISPLAY_OFF(13),
    PHONE_CALL_INTERRUPTION(14),
    VOIP_CALL_INTERRUPTION(15),
    VIEW_360_INTERRUPTION(16),
    MIC_BUG_PROCESSING(17),
    VIDEO_BUG_PROCESSING(18),
    CALL_RECORD_PROCESSING(19),
    VOIP_CALL_PROCESSING(20),
    FEATURE_NOT_SUPPORTED(21),
    DEVICE_MICROPHONE_INTERRUPTION(22),
    DEVICE_CAMERA_INTERRUPTION(23),
    FILE_CORRUPTED(24),
    DRAW_OVER_APP_PERMISSION_MISSING(25),
    SCHEDULING_FAILED(26),
    TEXT_ALERT_SUCCESS(27),
    TEXT_ALERT_DELETE_SUCCESS(28);
    
    fun getStatus(): String {
        return status.toString()
    }
}